config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    resources :notes, only: [:create], controller: 'tasks/notes'
  end
  resources :categories

  root 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Category < ApplicationRecord
  has_many :tasks
  
  validates :name, :description, presence: true
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@category) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    .row
      .col-12
        = f.input :name, label: 'Nombre'
    .row
      .col-12
        = f.input :description, as: :text, label: 'Descripción'
  .form-actions
    = f.button :submit, class: 'btn btn-info'

app/views/categories/edit.html.haml
.category.edit-page
  .card
    .card-body
      %h2 Editando categoría
      
      = render 'form'
      = link_to t('common.show'), @category, class: 'btn-interaction'
      \|
      = link_to t('common.back'), categories_path, class: 'btn-interaction'

app/views/categories/index.html.haml
.categories.index-page
  .card
    .card-body
      %h1 Lista de Categorías
      %table.table
        %thead
          %tr
            %th Nombre
            %th Descripción
            %th
            %th
            %th
        %tbody
          - @categories.each do |category|
            %tr
              %td= category.name
              %td= category.description
              %td= link_to t('common.show'), category
              %td= link_to t('common.edit'), edit_category_path(category)
              %td= link_to t('common.destroy'), category, :method => :delete, :data => { :confirm => t('common.are_you_sure') }
      %br
      .text-right
        = link_to 'Nueva Categoría', new_category_path, class: 'btn btn-info'

app/views/categories/new.html.haml
.category.new-page
  .card
    .card-body
      %h2 Nueva Categoría
      
      = render 'form'
      
      = link_to t('common.back'), categories_path, class: 'btn-interaction'

app/views/categories/show.html.haml
.category.show-page
  .card
    .card-body
      %p
        %b Nombre:
        = @category.name
      %p
        %b Descripción:
        = @category.description
      = link_to t('common.edit'), edit_category_path(@category), class: 'btn-interaction'
      \|
      = link_to t('common.back'), categories_path, class: 'btn-interaction'